### ISSUE TITLE
offset not defined, throws error in 'use strict' mode

### ISSUE THREAD

**Issue by mhkeller** [mapbox/dbf#23]
Because offset is not declared with `var` in [structure.js](https://github.com/mapbox/dbf/blob/35af04ba242e53aa7652561abca6145053f96cf8/src/structure.js#L58), this package breaks if you try to bundle it with something like rollup and you have `'use strict'`. The workaround is that you can tell rollup to not `'use strict'` but it's probably better that variables are declared.

**Comment by sheindel** [comment]
This is (finally) fixed in https://github.com/mapbox/dbf/pull/24. Thanks for the feedback!
