### ISSUE TITLE
Last Modified Date in Header off by 1

### ISSUE THREAD

**Issue by paupline** [mapbox/dbf#28]
I have used this node and works well except for any file exported in the month of January.  When trying to import the dbf into Word perfect, the file is reported to be of an unsupported format.  Upon review of the DBF file header, the Last Modified Date for the month of January shows a value of "00" and February is "01", etc...
Standard applications such as Excel and Quattro certainly don't care about the file header but Word Perfect seems to and throws a file format error.  I have attached 2 screenshots of the said error.  1 was created Jan 2018 and the other in Feb 2017 for reference.

![dbf file error feb 2017](https://user-images.githubusercontent.com/35075094/34532435-2173819a-f084-11e7-8218-5115eeed860b.jpg)
![dbf file error jan 2018](https://user-images.githubusercontent.com/35075094/34532436-2181e302-f084-11e7-9e6e-ea72501e5475.jpg)

**Comment by paupline** [comment]
FYI We managed to modify the code to adjust for the month value and are able to import into Word Perfect now for Mail Merge.

The issue lies with Java reporting the month as 0 for January (see attached image001)  This code was used to get the current month and pass it to the file header along with the current day and year.  In most cases as mentioned previously, standard applications such as Excel and Quattro do not consider the file header and will open it.  Word Perfect (any version) seems to evaluate the file header and if not formatted properly, it will be reported as an unsupported format.

![image002](https://user-images.githubusercontent.com/35075094/34538329-fa919be6-f099-11e7-9b8b-0ce77cb85cf8.png)
![image001](https://user-images.githubusercontent.com/35075094/34538331-fbf34a3e-f099-11e7-985f-16d08f61390f.png)

**Comment by bakednevada** [comment]
This was fixed in the pending PR https://github.com/mapbox/dbf/pull/20

**Comment by sheindel** [comment]
We have now merged this in! So I'm going to close this. Thanks for your input!
