### ISSUE TITLE
save on browser

### ISSUE THREAD

**Issue by fcpauldiaz** [mapbox/dbf#29]
How do I save the dbf file on the browser?

**Comment by MammutAlex** [comment]
You can use [saveAs](https://www.npmjs.com/package/file-saver) libe or write in vanillajs

saveAs example

     saveAs(new Blob([toBuffer(dbf.structure(data).buffer)], {
        type: "application/x-dbf;charset=utf-8"
    }), 'data.dbf');


vanillajs example


    var element = document.createElement('a');
    element.setAttribute('href', 
        'data:application/x-dbf;charset=utf-8,' + toBuffer(dbf.structure(data).buffer)
    );
    element.setAttribute('download', 'data.dbf');
    element.style.display = 'none';
    document.body.appendChild(element);
    element.click();
    document.body.removeChild(element);

**Comment by fcpauldiaz** [comment]
Nice
