### ISSUE TITLE
'offset' is not defined

### ISSUE THREAD

**Issue by iofirag** [mapbox/dbf#30]
i'm get the error 'offset' is not defined because i use strict mode.
so the fix for this kind of issue is to change

in dbf/src/structure.js

(line number 58)
from:

> offset = fieldDescLength + 32;

to:

> var offset = fieldDescLength + 32;

**Comment by SaiAnandPeketi-GIS** [comment]
I'm also getting this issue after upgrading, angular version from 12 to 14. Is it any fix available in the latest code?

**Comment by sheindel** [comment]
This is (finally) fixed in https://github.com/mapbox/dbf/pull/24. Thanks for the feedback!

**Comment by SaiAnandPeketi-GIS** [comment]
Hi Sheindel, Thanks for the fixes the issue. But still, I'm facing this issue while loading the npm package in my application and found that the code is not updated in it. Still "var" is missing in line number 58

https://www.npmjs.com/package/dbf?activeTab=code
![image](https://github.com/mapbox/dbf/assets/55728527/65ff0369-aa35-4e36-b84f-7f4e0e715090)

**Comment by sheindel** [comment]
Thanks for pinging. I'll see if I can get a new version deployed with these fixes. Hopefully will be available by next week sometime

**Comment by sheindel** [comment]
It's definitely patched in `dbf`, check `src/structure.js`.

Are you perhaps using something that uses `dbf`? Perhaps `shp-write`?

**Comment by jorosafi** [comment]
In case anyone else using `shp-write` runs into this ReferenceError, all you need to do is update it using `shp-write`'s new package location under the Mapbox organization -- https://www.npmjs.com/package/@mapbox/shp-write 

The old package location has been deprecated and does not appear include this `dbf` fix.
