### ISSUE TITLE
Open to maintaining

### ISSUE THREAD

**Issue by sheindel** [mapbox/dbf#38]
@davidtheclark Open to maintaining, please reach out

**Comment by sheindel** [comment]
@chriswhong you seem active on related Mapbox Github properties, can you provide any help? Can this officially be turned over to community maintenance?

**Comment by chriswhong** [comment]
Hi, I'll inquire about what that process entails.

**Comment by sheindel** [comment]
Yes, mostly as a dependency of `shp-write` (https://github.com/mapbox/shp-write), as others have noted in their PRs. There are also two closed issues from people who volunteered to be maintainers (per the note in the README)

https://github.com/mapbox/dbf/issues/37
https://github.com/mapbox/dbf/issues/35

**Comment by chriswhong** [comment]
Thanks for calling attention to this.  In the meantime maybe we can start with the current PRs.  Could you identify which ones are most important (or maybe all of them) and review?

**Comment by sheindel** [comment]
I think most could  be addressed by a maintainer in short order if you'd like to allow them, but this is the PR I came here for https://github.com/mapbox/dbf/pull/33

**Comment by Countdown369** [comment]
@sheindel, please let us know if you're still open to maintaining this; we've just gotten the go-ahead to add you with Write permissions to this repository.

**Comment by Countdown369** [comment]
If you are interested, here's an invite to the MapboxDevs Discord server, it'll be easier to communicate thru there than GitHub Issues :) https://discord.gg/uMpcC5RmJh
