### ISSUE TITLE
'offset' is not defined

### ISSUE THREAD

**Issue by SaiAnandPeketi-GIS** [mapbox/dbf#44]
I'm get the error 'offset' is not defined because I use strict mode. I saw that code is fixed for it but still not published it because whenever I'm download npm package "npm i dbf". I'm able to reproduce this issue and found that the code is not updated in npm package side. Still "var" is missing in line number 58

https://www.npmjs.com/package/dbf?activeTab=code
![image](https://github.com/mapbox/dbf/assets/55728527/d6114658-3449-4128-bcfa-fbf40549cdcf)

**Comment by sheindel** [comment]
Yes, this is fixed but not deployed. I'll see if I can get a deployment made. I don't work for Mapbox, they just allowed me to help manage development.

**Comment by SaiAnandPeketi-GIS** [comment]
Thanks. Please let me know if they allow to deploy the latest version.
